### ISSUE TITLE
Fatal Error: Cannot destructure property 'chainId' of 'this.networkController.getNetworkConfigurationByNetworkClientId(...)' as it is undefined. 

### ISSUE THREAD

**Issue by Aliceonly** [MetaMask/core#4593]
{
    "code": -32603,
    "message": "Cannot destructure property 'chainId' of 'this.networkController.getNetworkConfigurationByNetworkClientId(...)' as it is undefined.",
    "data": {
        "originalError": {}
    }
}

This error leads metamask can't open anymore, can't switch network, can't add network
always crush the metamask after entering the password

```
TypeError: Cannot destructure property 'chainId' of '(0 , t.useSelector)(...)' as it is undefined.
  at z (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:857888)
  at ga (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:61316)
  at Cs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:106147)
  at Au (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:92055)
  at Ou (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:91980)
  at Tu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:89328)
  at vu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:86072)
  at al (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:113703)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:114902
  at xu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:89679)
  at dl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:114887)
  at render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:116810)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:54554
```

**Comment by Gudahtt** [comment]
This problem was tracked here: https://github.com/MetaMask/metamask-extension/issues/26326
